languaje: node_js

cache:
  directories:
    - ./node_modules
    - ~/.npm

node_js:
  - "12"

git:
  depth: 3

script:
  # - yarn lint # travis maneja yarn si usas npm no importa
  - yarn test-headless # UnitTest
  - yarn postinstall

notification:
  email:
    reciepients:
      - anedacos@espol.edu.ec
    on_sucsess: always
    on_failure: always

deploy:
  provider: heroku
  skip_cleanup: true
  keep_history: true
  # COMMIT_MESSAGE: "Deploy del proyecto"
  api_key:
    2667dee5-cb74-4b61-b622-ff0b1ed24d27
    # secure: "secretkey"
  app: interoc-frontend

  on:
    repo: anedacos/ProyectoIS2
    # master: interoc-frontend-staging
    # production: interoc-frontend-production
  # local_dir: dist/
  # target_branck:gh
